import Foundation

/// Represents a financial transaction (income, expense, or transfer).
///
/// A transaction is an immutable record of a financial event. Monetary amounts
/// are always stored as `Decimal` to avoid floating-point rounding errors.
/// Location fields are optional and stored as raw coordinates rather than a
/// platform-specific type to keep this model platform-agnostic.
public struct Transaction: Identifiable, Sendable, Hashable, Codable {
    /// Unique identifier for the transaction.
    public let id: UUID

    /// The absolute (positive) monetary amount of the transaction in the account's currency.
    public var amount: Decimal

    /// Whether this is an income, expense, or transfer transaction.
    public var type: TransactionType

    /// The category this transaction belongs to.
    ///
    /// Required for all transaction types, including transfers (use a dedicated
    /// "Transfer" category). This enforces consistent categorisation across the app.
    public var categoryID: UUID

    /// The source account for this transaction.
    public var accountID: UUID

    /// The destination account for a transfer transaction.
    ///
    /// Must be set when `type` is `.transfer` and must differ from `accountID`.
    public var toAccountID: UUID?

    /// An optional free-text note attached to the transaction.
    public var note: String

    /// The date and time when the financial event occurred.
    public var date: Date

    /// Whether this transaction was generated by a recurring rule.
    public var isRecurring: Bool

    /// UUIDs of tags applied to this transaction.
    public var tags: [UUID]

    /// WGS-84 latitude of the location where the transaction occurred.
    ///
    /// Stored as `Double` because it represents a geographic coordinate,
    /// not a monetary value. Valid range: -90.0 … 90.0.
    public var latitude: Double?

    /// WGS-84 longitude of the location where the transaction occurred.
    ///
    /// Stored as `Double` because it represents a geographic coordinate,
    /// not a monetary value. Valid range: -180.0 … 180.0.
    public var longitude: Double?

    /// Arbitrary key-value metadata for extensibility (e.g., receipt URLs, merchant IDs).
    public var metadata: [String: String]?

    /// Soft delete timestamp. When set, the transaction is considered deleted
    /// and should be excluded from all normal queries.
    public var deletedAt: Date?

    /// Date when the transaction record was first created.
    public var createdAt: Date

    /// Date when the transaction record was last modified.
    public var updatedAt: Date

    /// Creates a new transaction.
    ///
    /// - Parameters:
    ///   - id: Unique identifier. Defaults to a new UUID.
    ///   - amount: Positive monetary amount in the account's currency.
    ///   - type: Income, expense, or transfer.
    ///   - categoryID: Required category identifier.
    ///   - accountID: Source account identifier.
    ///   - toAccountID: Destination account for transfers. Defaults to nil.
    ///   - note: Optional free-text note. Defaults to empty string.
    ///   - date: Date the financial event occurred. Defaults to now.
    ///   - isRecurring: Whether generated by a recurring rule. Defaults to false.
    ///   - tags: Tag UUIDs applied to this transaction. Defaults to empty array.
    ///   - latitude: Optional WGS-84 latitude. Defaults to nil.
    ///   - longitude: Optional WGS-84 longitude. Defaults to nil.
    ///   - metadata: Optional key-value metadata. Defaults to nil.
    ///   - deletedAt: Soft delete timestamp. Defaults to nil.
    ///   - createdAt: Record creation date. Defaults to now.
    ///   - updatedAt: Record last-modified date. Defaults to now.
    public init(
        id: UUID = UUID(),
        amount: Decimal,
        type: TransactionType,
        categoryID: UUID,
        accountID: UUID,
        toAccountID: UUID? = nil,
        note: String = "",
        date: Date = Date(),
        isRecurring: Bool = false,
        tags: [UUID] = [],
        latitude: Double? = nil,
        longitude: Double? = nil,
        metadata: [String: String]? = nil,
        deletedAt: Date? = nil,
        createdAt: Date = Date(),
        updatedAt: Date = Date()
    ) {
        self.id = id
        self.amount = amount
        self.type = type
        self.categoryID = categoryID
        self.accountID = accountID
        self.toAccountID = toAccountID
        self.note = note
        self.date = date
        self.isRecurring = isRecurring
        self.tags = tags
        self.latitude = latitude
        self.longitude = longitude
        self.metadata = metadata
        self.deletedAt = deletedAt
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }
}

/// The classification of a financial transaction.
public enum TransactionType: String, Sendable, CaseIterable, Codable, Hashable {
    /// Money received into an account.
    case income

    /// Money spent from an account.
    case expense

    /// Money moved between two accounts owned by the same user.
    case transfer

    /// A human-readable label for the transaction type.
    public var displayName: String {
        switch self {
        case .income: return "Income"
        case .expense: return "Expense"
        case .transfer: return "Transfer"
        }
    }
}
